project:
  type: website
  output-dir: docs

website:
  title: "Haobo Ren"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contact.qmd

format:
  html:
    theme: pandoc
    css: styles.css
    toc: true



